// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDajQNRmVWgmqgw5j53UegXydmi1afYZsk',
    appId: '1:413440393912:web:c99747687db18fe46aea4d',
    messagingSenderId: '413440393912',
    projectId: 'bim-tracker',
    authDomain: 'bim-tracker.firebaseapp.com',
    storageBucket: 'bim-tracker.appspot.com',
    measurementId: 'G-DFMZSSNLMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPMqD9IczlXKMtoaz7E2SNul8p5Vr2NYw',
    appId: '1:413440393912:android:635c350a7e9d760d6aea4d',
    messagingSenderId: '413440393912',
    projectId: 'bim-tracker',
    storageBucket: 'bim-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2TMjee9jLCsIV9c9BWY7jkadzdFf2Lo',
    appId: '1:413440393912:ios:d60ae73fca74c4506aea4d',
    messagingSenderId: '413440393912',
    projectId: 'bim-tracker',
    storageBucket: 'bim-tracker.appspot.com',
    iosBundleId: 'com.example.bmiTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2TMjee9jLCsIV9c9BWY7jkadzdFf2Lo',
    appId: '1:413440393912:ios:e4bc72d3f2e81bb96aea4d',
    messagingSenderId: '413440393912',
    projectId: 'bim-tracker',
    storageBucket: 'bim-tracker.appspot.com',
    iosBundleId: 'com.example.bmiTracker.RunnerTests',
  );
}
